def get_question(n, t):
    return a[n][t]

a = [[0 for i in range(10)] for i in range(15)]

# a[i][j] = ["question", "option A", "option B", "option C", "option D", "correct answer"]

a[0][0] = ["Thợ điện có thể đặt những gì?","Bàn","Gables","Cables","Stables","Cables"];
a[0][1] = ["Đĩa compact thường được biết đến bằng chữ viết tắt nào?","CD","COD","CDIS","COMPD","CD"]
a[0][2] = ["Màu nào được dùng làm thuật ngữ để mô tả thị trường bất hợp pháp đối với hàng hiếm?","Blue","Red","Black","White","Black"]
a[0][3] = ["Diễn viên điện ảnh muốn nhận giải nào trong số này?","Oliver","Oscar","Oliphant","Osbert","Oscar"]
a[0][4] = ["Bạn mong đợi được chào đón bằng từ 'bonjour' ở quốc gia nào?","Italy","France","Spain","Wales","France"]
a[0][5] = ["Từ nào theo sau 'Bắc' và 'Nam' để đặt tên cho hai lục địa?","Châu Phi","Mỹ","Châu Á","Úc","Mỹ"]
a[0][6] = ["Quốc gia nào không phải là một hòn đảo?","Madagascar","Cuba","Đức","Jamaica","Đức"]
a[0][7] = ["Bạn thường làm gì với chiếc mũ nồi?","Ăn nó","Chơi nó","Ngồi lên nó","Mặc nó","Mặc nó"]
a[0][8] = ["Cái nào trong số này là công cụ để tạo hình và làm mịn gỗ?","Train","Máy bay","Ô tô","Xe đạp","Máy bay"]
a[0][9] = ["Bạn mong đợi nhìn thấy gì ở Thủy cung Luân Đôn?","Hoa","Cây cối","Con lăn hơi nước","Cá","Cá"]

a[1][0] = ["Cái nào không phải là loại linh dương?","Gorilla","Gerenuk","Gemsbok","Gnu","Gorilla"]
a[1][1] = ["Rioja là loại gì?","Bánh mì","Rau","Rượu vang","Hạt","Rượu vang"]
a[1][2] = ["Đức là tên La Mã của quốc gia châu Âu thời hiện đại nào?","Pháp","Áo","Đức","Tây Ban Nha","Đức"]
a[1][3] = ["Điểm thu hút trả lương cao nhất tại Vương quốc Anh năm 2002 là gì?","London Nose","London Mouth","London Eye","London Ear","London Eye"]
a[1][4] = ["Đặc điểm địa lý nào sau đây là núi?","Kilimanjaro","Danube","Amazon","Nile","Kilimanjaro"]
a[1][5] = ["Hình thức âm nhạc nào trong số này là hình thức âm nhạc phổ biến?","Quốc gia & Phương Đông","Vương quốc & Phương Bắc","Đất đai & Phương Nam","Quốc gia & Phương Tây","Quốc gia & Phương Tây"]
a[1][6] = ["Cái nào trong số này là thuật ngữ chung cho một chương trình tập thể dục?","Stayable","Giữ dáng","Tiếp tục thành thạo","Giữ dáng","Giữ dáng" ]
a[1][7] = ["Tên bảng điều khiển trên ô tô là gì?","Chargeboard","Sprintboard","Dashboard","Jogboard","Dashboard"]
a[1][8] = ["Bản sao nào có thể được dùng để mô tả một cái gì đó giống hệt nhau?","Oxygen","Hydrogen","Nitrogen","Carbon","Carbon"]
a[1][9] = ["Chuỗi khách sạn quốc tế nào?","Four Tops","Four Pennies","Four Seasons","Four Posters","Four Seasons"]

a[2][0] = ["Món nào trong số này là món cay của Ấn Độ?","Spaghetti","Biriani","Bellini","Crostini","Biriani"]
a[2][1] = ["Quốc gia nào không nằm trong Vòng Bắc Cực?","Na Uy","Phần Lan","Hy Lạp","Sweeden","Hy Lạp"]
a[2][2] = ["Trong phim nào một chiếc xe buýt phải tiếp tục di chuyển với tốc độ 50 dặm một giờ để nó không phát nổ?","Tốc độ","Velocity","Tempo","Lực đẩy","Tốc độ "]
a[2][3] = ["Một người lớn tuổi đôi khi được mô tả là 'dài ...'?","Răng","Mắt","Tóc","Mũi","Răng"]
a[2][4] = ["Theo câu nói, món nào sau đây là 'món ăn nguội ngon nhất'?","Revenge","Bánh Cottage","Custard","Hầm","Trả thù"]
a[2][5] = ["Để biết những điều cơ bản của một chủ đề là 'biết ...'?","ABC","HIJ","KLM","QRS","ABC"]
a[2][6] = ["Cái nào trong số này là sản phẩm thay thế bơ được làm bằng dầu thực vật?","Margaret","Margarine","Margarita","Margate","Margarine"]
a[2][7] = ["Hoàn thành tiêu đề của bộ phim Disney phát hành năm 2003, 'Cướp biển ...'?","Biển Đen","Atlantic","English Channel","Caribbean","Caribbean "]
a[2][8] = ["Quốc gia nào trong số này không tổ chức cuộc đua Công thức 1 Grand Prix năm 2003?","Monaco","Pháp","Ý","Madagascar","Madagascar"]
a[2][9] = ["Mặt sân nào không được công nhận cho quần vợt?","Cỏ","Linoleum","Đất sét","Xi măng","Linoleum"]

a[3][0] = ["Cái nào sau đây là xúc xích nhỏ?","Maraschino","Chipolata","Risotto","Gazpacho","Chipolata"]
a[3][1] = ["Thuật ngữ chung để chỉ các diễn viên xuất hiện trong một bộ phim hoặc vở kịch là gì?","Cast","Band","Group","Clique","Cast"]
a[3][2] = ["Người ta nói bạn sẽ phạm điều gì khi kết bạn với một người lạ?","The Ice","The Snow","The Hail","The Frost","The Ice "]
a[3][3] = ["Theo truyền thống, người ta dùng chân để ép nước từ loại trái cây nào?","Dứa","Anh đào","Nho","Lê gai","Nho"]
a[3][4] = ["'going, going, gone' liên quan nhiều nhất đến hoạt động nào?","Đấu giá","Làm vườn","Đua ngựa","Quyền anh","Đấu giá" ]
a[3][5] = ["Trụ sở chính của Bộ Quốc phòng Hoa Kỳ ở đâu?","Tam giác","Hình chữ nhật","Lầu Năm Góc","Khối mười hai mặt","Lầu Năm Góc"]
a[3][6] = ["Cái nào trong số này là lý thuyết về sự hình thành vũ trụ?","Big Bong","Big Bang","Big Ben","Big Bertha","Big Bang"]
a[3][7] = ["Phương tiện nào sau đây có nhiều khả năng chạy trên đường ray bánh xích nhất?","Ô tô","Train","Máy ủi","Xe đạp","Máy ủi"]
a[3][8] = ["Kênh nào trong số này là kênh truyền hình vệ tinh?","Trademark","Landmark","Hallmark","Dirtymark","Hallmark"]
a[3][9] = ["Cái nào trong số này nằm ở phía sau cổ họng của bạn?","Deltoids","Tabloid","Adenoids","Solenoids","Adenoids"]

a[4][0] = ["Loại steroid nào có tác dụng tạo protein?","Carbolic","Shambolic","Anabolic","Diabolic","Anabolic"]
a[4][1] = ["Cái gì sẽ được sử dụng để tăng tín hiệu điện?","Ambrosia","Nhà hát vòng tròn","Amphetamine","Bộ khuếch đại","Bộ khuếch đại"]
a[4][2] = ["Có bao nhiêu dòng được sử dụng cho dấu 'bằng' trong ký hiệu toán học?","One","Two","Three","Bốn","Hai"]
a[4][3] = ["Nguyên tố hóa học nào được đặt theo tên của một hành tinh trong hệ mặt trời của chúng ta?","Venusium","Jupiterium","Uranium","Saturnium","Uranium"]
a[4][4] = ["Sao nào không phải là loại sao?","Người khổng lồ đỏ","Sao lùn trắng","Sao lùn đỏ","Yêu tinh xanh","Yêu tinh xanh"]
a[4][5] = ["'Freak of Nature' là tựa đề album ăn khách toàn cầu của ai?","Anastacia","Caucasia","Dysphasia","Phoenicia","Anastacia"]
a[4][6] = ["Robbie Williams từng là thành viên của nhóm nào trong số này?","Ouch!","Take That","Wham!","Biff!","Take That"]
a[4][7] = ["Cái nào trong số này là nhạc cụ ba dây?","Balaclava","Balakirev","Balalaika","Balanchine","Balalaika"]
a[4][8] = ["Cái nào trong số này là thuật ngữ chỉ diễn viên?","Equestrian","Thespian","Pedestrian","Martian","Thespian"]
a[4][9] = ["Cái nào trong số này có thể được rắc lên bánh gạo?","Cinnabar","Cinnamon","Cincinnati","Cinerama","Cinnamon"]

a[5][0] = ["Double Gloucester là gì?","Trò chơi bài","Phô mai","Hàng rào rất dày","Mái tranh","Phô mai"]
a[5][1] = ["Loại nào trong số này xuất hiện lần đầu trên thị trường vào năm 1937?","Posh Spice","Scary Spice","Baby Spice","Old Spice","Old Spice"]
a[5][2] = ["Người mua sắm bừa bãi những bộ quần áo mới nhất là 'thời trang ...'?","Nhân chứng","Thủ phạm","Nghi ngờ","Nạn nhân","Nạn nhân"]
a[5][3] = ["Ai không phải là hoàng đế La Mã?","Hadrian","Parallax","Claudius","Tiberius","Parallax"]
a[5][4] = ["Đảo nào được gọi là Kriti theo ngôn ngữ của nó?","Crete","Corsica","Corfu","Cuba","Crete"]
a[5][5] = ["Từ 'vua' trong tiếng Pháp là gì?","Kaiser","Duc","Herzog","Roi","Roi"]
a[5][6] = ["Thuật ngữ nào được sử dụng cho toàn bộ nền của lá cờ?","Meadow","Lea","Pasture","Field","Field"]
a[5][7] = ["Thuật ngữ nào chỉ một bộ phim thất bại về doanh thu phòng vé?","Grenade","Mine","Bomb","Shell","Bomb"]
a[5][8] = ["Từ nào đôi khi được dùng để chỉ món tráng miệng?","Befores","whiles","Afters","Nevers","Afters"]
a[5][9] = ["Những sinh vật nào được nuôi trong chuồng chim theo truyền thống?","Chim","Cá","Bò sát","Côn trùng","Chim"]

a[6][0] = ["Cụm từ tiếng Latin 'compos mentis' có nghĩa là 'âm thanh ...'?","Lời khuyên","Sức khỏe","Tâm trí","Khu vườn","Tâm trí"]
a[6][1] = ["Vật liệu nào được sử dụng để làm đường?","Macaroni","Macabre","Macadam","Macdonald",""]
a[6][2] = ["Mèo thường mắc phải bệnh nào trong số này?","Fastballs","Hairballs","Meatballs","Curveballs","Hairballs"]
a[6][3] = ["Đơn vị nào không phải là đơn vị đo điện SI?","Volt","Ampere","Ohm","Gallon","Gallon"]
a[6][4] = ["Natri cacbonat thường được biết đến với cái tên nào?","Bánh quy soda","Bánh mì soda","Soda giặt","Vôi và soda","Soda giặt"]
a[6][5] = ["Theo câu tục ngữ, cái nồi canh không bao giờ làm được điều gì?","Đổ","Tràn","Sôi","Rỗng","Sôi"]
a[6][6] = ["Bánh kếp chiên, nhồi Mexico là gì?","Waco","Saki","Taco","Pesto","Taco"]
a[6][7] = ["Ai đã đặt tên cho lục địa này?","Europa Bellini","Amerigo Vespucci","Africo Tintorini","Asio Canelli","Amerigo Vespucci"]
a[6][8] = ["Cảng nào là cảng chính của Athens?","Amadeus","Nicodemus","Piraeus","Celsius","Piraeus"]
a[6][9] = ["Con sông nào trong số này không phải là sông châu Âu?","Danube","Rhine","Seine","Missouri","Missouri"]

a[7][0] = ["Thành phố thủ đô nào của Nam Mỹ?","Paprika","Mustard","Cayenne","Saffron","Cayenne"]
a[7][1] = ["Từ tiếng Pháp nào được dùng để chỉ một nhóm hoặc lớp được chọn?","Elan","Eglise","Ecole","Elite","Elite"]
a[7][2] = ["Vật liệu tổng hợp bền và bền nào?","PVC","PTO","POW","PBX","PVC"]
a[7][3] = ["Giống chó nào trước đây được sử dụng làm chó huấn luyện viên?","Croatian","Dalmatian","Montenegran","Bosnian","Dalmatian"]
a[7][4] = ["Chim thiên đường có nguồn gốc từ hòn đảo nào trong số những hòn đảo này?","Anglesey","New Guinea","Iceland","Sicily","New Guinea"]
a[7][5] = ["Bộ phim nào trong số này là phim hoạt hình máy tính của Disney năm 2003?","Định vị Remo","Khám phá Lemo","Khai quật Zemo","Đi tìm Nemo","Tìm Nemo"]
a[7][6] = ["Ai đã phát hành album có tên 'Justified' vào năm 2003?","Britney Spears","Justin Timberlake","Gareth Gates","Victoria Beckham","Justin Timberlake"]
a[7][7] = ["Phụ đề của bộ phim năm 2003 'Legally Blonde 2' là gì?","Blue Red & Blonde","Pink Blue & Blonde","Green Red & Blonde","Red White & Tóc vàng","Đỏ trắng & vàng"]
a[7][8] = ["Bạn thường làm gì với Liebfraumilch?","Uống nó","Chơi một giai điệu trên nó","Lái nó","Ngồi lên nó","Uống nó"]
a[7][9] = ["Cái nào trong số này không phải là loại sơn dùng trong trang trí?","Gloss","Satin","Silk","Damask","Damask"]

a[8][0] = ["Tên ngôi sao nào là đảo chữ của một quốc gia châu Âu?","Demi Moore","Meg Ryan","Mira Sorvino","Minnie Driver","Meg Ryan"]
a[8][1] = ["Đòn nào không phải là đòn đấm trái luật trong quyền anh?","Butt","Elbow","Jab","Palm","Jab"]
a[8][2] = ["Từ nào trong số những từ này được sử dụng để nhận dạng máy chủ Internet?","Realm","Tỉnh","Kingdom","Miền","Miền"]
a[8][3] = ["Tên thay thế nào cho đậu phộng?","Earthnut","Soilnut","Groundnut","Allnut","Groundnut"]
a[8][4] = ["Hoàn thành tên của nhóm nhạc rock nổi tiếng, Radio...?","Arm","Leg","Foot","Head","Head"]
a[8][5] = ["Hoàn thành tên của ca sĩ người Anh, Mica ... ?","Berlin","Madrid","Dublin","Paris","Paris"]
a[8][6] = ["Họ của ca sĩ nhạc pop Beyonce là gì?","Cowles","Fowles","Knowles","Dowles","Knowles"]
a[8][7] = ["Ở Hoa Kỳ, 'G-man' sẽ làm việc cho tổ chức nào?","FBI","NBA","NFL","MFI","FBI"]
a[8][8] = ["Có nguồn gốc từ Ý, mortadella là loại thực phẩm gì?","Xúc xích","Pasta","Phô mai","Bánh ngọt","Xúc xích"]
a[8][9] = ["Tên địa điểm nào trong số này có nghĩa là 'nhà trắng'?","Canberra","Canada","Casablanca","Canterbury","Casablanca"]

a[9][0] = ["Algeria có đường bờ biển ở biển nào?","Adriatic","Caspian","Baltic","Địa Trung Hải","Địa Trung Hải"]
a[9][1] = ["Từ tiếng Pháp của nước Anh là gì?","Angleterre","Etats-Unis","Inglaterra","Bretagne","Angleterre"]
a[9][2] = ["Cái nào trong số này mô tả những người giàu có và nổi tiếng?","Glitterati","Hoi polloi","Thành lập","Paparazzi","Glitterati"]
a[9][3] = ["Thuật ngữ tiếng Ý nào được dùng để mô tả bức tranh trên thạch cao ướt?","Frappe","Fresco","Fredo","Frisson","Fresco"]
a[9][4] = ["Trong bộ phim nào năm 2003, Jim Carrey được Chúa ban cho sức mạnh thần thánh?","Harry the Holy","Al Omnipotent","Gordon đóng vai Chúa","Bruce Đấng Toàn Năng","Bruce Toàn Năng"]
a[9][5] = ["Người Nam Phi gốc Hà Lan được đặt tên gì?","Moors","Boers","Creoles","Voortrekkers","Boers"]
a[9][6] = ["Từ 'QWERTY' gắn liền với từ gì?","Chủ nghĩa Cộng sản","Nghệ thuật hiện đại","Bàn phím máy tính","Rượu vang","Bàn phím máy tính"]
a[9][7] = ["Đèn màu gì chỉ báo mạn trái của tàu?","Vàng","Trắng","Xanh","Đỏ","Đỏ"]
a[9][8] = ["Thành phố nào ở Hoa Kỳ là bối cảnh cho bộ phim sitcom truyền hình 'Taxi'?","Boston","Dallas","Los Angeles","New York","New York"]
a[9][9] = ["Một tấn hệ mét bao gồm 1000 cái gì?","Stones","Kilôgam","Pounds","Gram","Kilôgam"]

a[10][0] = ["Nguyên tố nào có ký hiệu hóa học là Co?","Carbon","Canxi","Chromium","Cobalt","Cobalt"]
a[10][1] = ["Theo Kinh thánh, ai trong số này không phải là tổng lãnh thiên thần?","Michael","Raphael","Gabriel","Ishmael","Ishmael"]
a[10][2] = ["Danh hiệu nào trong số này được ban cho Margaret Thatcher?","Nữ hầu tước","Nữ công tước","Nữ nam tước","Nữ bá tước","Nữ nam tước"]
a[10][3] = ["Jimmy nào, sinh năm 1948 ở Jamaica, đã trở thành ngôi sao nhạc reggae?","Edge","Mount","Cliff","Tor","Cliff"]
a[10][4] = ["Tác giả nào trong số này không bị tống vào tù?","Oscar Wilde","John Bunyan","Agatha Christie","Brendan Behan","Agatha Christie"]
a[10][5] = ["Con ngựa thành Troy huyền thoại chứa đựng những gì?","Horses","Gold","Wheat","Soldiers","Soldiers"]
a[10][6] = ["Đó là trận chiến nào trong Chiến tranh giành độc lập của Hoa Kỳ?","Fairway Hill","Green Hill","Bunker Hill","Rough Hill","Bunker Hill"]
a[10][7] = ["Quốc gia Đông Âu ngày nay không thuộc Liên Xô cũ?","Hungary","Lithuania","Ukraine","Latvia",""]
a[10][8] = ["Núi Ô-liu nằm ngay phía đông thành phố nào?","Jerusalem","Moscow","Hong Kong","Paris","Jerusalem"]
a[10][9] = ["Trong kinh tế học, chữ 'D' viết tắt của GDP có nghĩa là gì?","Quốc phòng","Daily","Dual","Trong nước","Trong nước"]

a[11][0] = ["Trong hội họa, màu nào không phải là màu thứ cấp?","Xanh","Cam","Tím","Đỏ","Đỏ"]
a[11][1] = ["Loài khủng long nào có thể bay?","Allosaurus","Diplodocus","Stegosaurus","Pterodactyl","Pterodactyl"]
a[11][2] = ["Tổng thống nào được bầu vào nhiệm kỳ thứ sáu vào tháng 3 năm 2003?","George W Bush","Fidel Castro","Mary McAleese","Vladimir Putin","Fidel Castro" ]
a[11][3] = ["Cái gì, vào tháng 8 năm 2003, 'Sobig.F'?","Hãng hàng không mới","Virus máy tính","Đào khảo cổ học","Thiên thạch","Virus máy tính"]
a[11][4] = ["Tháng 10 năm 2003, quốc gia nào trở thành quốc gia thứ ba đưa con người vào vũ trụ?","Nhật Bản","Nam Phi","Úc","Trung Quốc","Trung Quốc"]
a[11][5] = ["Bạn thường làm gì với mai tai?","Ăn nó","Mặc nó","Uống nó","Hát","Uống nó"]
a[11][6] = ["Tên của hai sứ mệnh NASA gửi tới sao Hỏa vào năm 1975 là gì?","Viking","Visigoth","Saxon","Hun","Viking"]
a[11][7] = ["Cái nào trong số này là bảo hiểm ô tô quốc tế?","Thẻ vàng","Thẻ xanh","Thẻ xanh","Thẻ đỏ","Thẻ xanh"]
a[11][8] = ["Sân bóng đá theo luật Úc có hình dạng như thế nào?","Hình chữ nhật","Hình tròn","Diamond","Hình bầu dục","Hình bầu dục"]
a[11][9] = ["Giải nào không phải là một trong 'Chuyên ngành' của gôn?","USPGA","US Masters","US Open","US Pro-Am","US Pro-Am"]

a[12][0] = ["Nghiên cứu địa chấn học là gì?","Động đất","Thủy triều","Mây","Núi lửa","Động đất"]
a[12][1] = ["David Gates là giọng ca chính của ban nhạc Mỹ nào?","Yeast","Money","Dough","Bread","Bread"]
a[12][2] = ["Cái nào trong số này không phải là cây ngũ cốc?","Lúa mì","Kê","Ngô","Đậu nành","Đậu nành"]
a[12][3] = ["Trên bàn phím máy tính tiêu chuẩn, chữ cái nào nằm giữa 's' và 'f'?","c","d","e","r","d"]
a[12][4] = ["'Hộp đựng thuốc' là loại phụ kiện thời trang như thế nào?","Khăn quàng cổ","Mũ","Thắt lưng","Váy","Mũ"]
a[12][5] = ["Cuộc xâm lược thành công cuối cùng vào nước Anh là vào năm nào?","55 TCN","1066","1812","1914","1066"]
a[12][6] = ["Không quân Đức được đặt tên gì?","Blitzkrieg","Luftwaffe","Panzer","Messerschmidt","Luftwaffe"]
a[12][7] = ["Nếu đến sân bay Split, bạn sẽ ở quốc gia nào?","Slovakia","Slovenia","Croatia","Hungary","Croatia"]
a[12][8] = ["Đại dương nào trong số này là nhỏ nhất?","Bắc Cực","Thái Bình Dương","Đại Tây Dương","Ấn Độ","Bắc Cực"]
a[12][9] = ["Dolomites là một dãy núi ở phía đông bắc của quốc gia nào?","Ba Lan","Thổ Nhĩ Kỳ","Đức","Ý","Ý"]

a[13][0] = ["El Alamein nằm ở quốc gia nào?","Syria","Lebanon","Ai Cập","Ả Rập Saudi","Ai Cập"]
a[13][1] = ["Sa mạc nào trong số này thuộc Hoa Kỳ?","Sa mạc Atacama","Sa mạc Gobi","Sa mạc Sahara","Sa mạc Mojave","Sa mạc Mojave"]
a[13][2] = ["Thành phố Tucson nằm ở tiểu bang nào của Hoa Kỳ?","Arizona","Kansas","Texas","Colorado","Arizona"]
a[13][3] = ["Khoảng 61% dân số thế giới sống ở lục địa nào?","Bắc Mỹ","Châu Âu","Châu Á","Châu Phi","Châu Á"]
a[13][4] = ["Tên tiếng Anh của bộ phim Brazil 'Cidade de Deus' là gì?","Church","City of God","Angels","Thành phố vĩnh cửu","Thành phố của Chúa"]
a[13][5] = ["Vận động viên quần vợt Alex Corretja có quốc tịch gì?","Peru","Chilean","Người Brazil","Tây Ban Nha","Tây Ban Nha"]
a[13][6] = ["Đội Edmonton Oilers chơi môn thể thao nào?","Bóng rổ","Bóng chày","Bóng bầu dục Mỹ","Khúc côn cầu trên băng","Khúc côn cầu trên băng"]
a[13][7] = ["Môn thể thao nào sử dụng hệ thống xuất phát Cây Giáng sinh?","Công thức 1","Motocross","Đua xe kéo","Đua xe ô tô","Đua xe kéo"]
a[13][8] = ["Đội đua Công thức 1 nào giành được nhiều danh hiệu Nhà xây dựng nhất?","Williams","Ferrari","Lotus","McLaren","Ferrari"]
a[13][9] = ["Quần đảo Galapagos nằm ở đại dương nào?","Atlantic","Indian","Bắc Cực","Thái Bình Dương","Thái Bình Dương"]

a[14][0] = ["Sa mạc Atacama nằm ở quốc gia nào?","Mexico","Morocco","Chile","Mongolia","Chile"]
a[14][1] = ["Phnom Penh là thủ đô của nước nào?","Việt Nam","Thái Lan","Campuchia","Malaysia","Cambodia"]
a[14][2] = ["Buổi chiều là một thuật ngữ cổ chỉ thời gian nào trong ngày?","Morning","Buổi tối","Noon","Đêm","Buổi tối"]
a[14][3] = ["Nguyên tố hóa học nào được đặt theo tên của một vị thần Bắc Âu?","Uranium","Neptunium","Osmium","Thorium","Thorium"]
a[14][4] = ["Cái tên nào được đặt cho sự chia ly thân thiện giữa Slovakia và Cộng hòa Séc?","Satin Split","Velvet Ly hôn","Tách lụa","Damask Chia tay","Velvet Ly hôn"]
a[14][5] = ["Cơ quan tương đương của Vương quốc Anh với CIA tại Hoa Kỳ là gì?","SAS","MI5","CND","MI6","MI6"]
a[14][6] = ["Cái gì nằm ở trung tâm của mô hình nhật tâm của hệ mặt trời?","Trái đất","Mặt trời","Mặt trăng","Sao Bắc Đẩu","Mặt trời"]
a[14][7] = ["Ai đã tham gia chuyến lưu diễn 'Blonde Ambition' vào năm 1990?","Blondie","Cher","Annie Lennox","Madonna","Madonna"]
a[14][8] = ["Xì trum đến từ nước nào?","Thụy Điển","Bỉ","Pháp","Đan Mạch","Bỉ"]
a[14][9] = ["Những lời cuối cùng nổi tiếng của nhà soạn nhạc nổi tiếng là 'Tôi sẽ nghe thấy trên thiên đường'?","Wagner","Mozart","Albinoni","Beethoven","Beethoven"]